/* Verilog netlist generated by SCUBA Diamond_1.3_Production (92) */
/* Module Version: 3.1 */
/* C:/lscc/1.3_20110802-1_3p.92/diamond/1.3/ispfpga/bin/nt/scuba -w -arch xo2c00 -n pmi_addsubXo88 -bb -bus_exp 7 -type addsub -width 8 -unsigned -port ci -port co -pmi -lang verilog  */
/* Mon Oct 24 16:54:29 2011 */


`timescale 1 ns / 1 ps
module pmi_addsubXo88 (DataA, DataB, Cin, Add_Sub, Result, Cout, 
    Overflow);
    input wire [7:0] DataA;
    input wire [7:0] DataB;
    input wire Cin;
    input wire Add_Sub;
    output wire [7:0] Result;
    output wire Cout;
    output wire Overflow;

    wire scuba_vhi;
    wire ci_k;
    wire co0;
    wire co1;
    wire co2;
    wire co3;
    wire add_sub_inv;
    wire co4d;
    wire co4;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    XNOR2 XNOR2_t0 (.A(Cin), .B(Add_Sub), .Z(ci_k));

    INV INV_0 (.A(Add_Sub), .Z(add_sub_inv));

    FADSU2 addsub_0 (.A0(Cin), .A1(DataA[0]), .B0(ci_k), .B1(DataB[0]), 
        .BCI(scuba_vlo), .CON(Add_Sub), .BCO(co0), .S0(), .S1(Result[0]));

    FADSU2 addsub_1 (.A0(DataA[1]), .A1(DataA[2]), .B0(DataB[1]), .B1(DataB[2]), 
        .BCI(co0), .CON(Add_Sub), .BCO(co1), .S0(Result[1]), .S1(Result[2]));

    FADSU2 addsub_2 (.A0(DataA[3]), .A1(DataA[4]), .B0(DataB[3]), .B1(DataB[4]), 
        .BCI(co1), .CON(Add_Sub), .BCO(co2), .S0(Result[3]), .S1(Result[4]));

    FADSU2 addsub_3 (.A0(DataA[5]), .A1(DataA[6]), .B0(DataB[5]), .B1(DataB[6]), 
        .BCI(co2), .CON(Add_Sub), .BCO(co3), .S0(Result[5]), .S1(Result[6]));

    FADSU2 addsub_4 (.A0(DataA[7]), .A1(scuba_vlo), .B0(DataB[7]), .B1(add_sub_inv), 
        .BCI(co3), .CON(Add_Sub), .BCO(co4), .S0(Result[7]), .S1(Cout));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FADD2B addsubd (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(co4), .COUT(), .S0(co4d), .S1());



    // exemplar begin
    // exemplar end

endmodule
