/* Verilog netlist generated by SCUBA ispLever_v61_SP1_Build (17) */
/* Module Version: 3.4 */
/* C:\ispLEVER_6_1_ver37\ispfpga\bin\nt\scuba.exe -w -n pll_clk -lang verilog -synth synplify -arch mg5a00 -type pll -fin 200 -phase_cntl STATIC -fclkop 200 -fclkop_tol 0.0 -fb_mode CLOCKTREE -noclkos -noclkok -use_rst -noclkok2 -e  */
/* Tue Feb 13 14:46:37 2007 */


`timescale 1 ns / 1 ps
module clk_pll_xp2 (CLK, RESET, CLKOP, LOCK);
    input CLK;
    input RESET;
    output CLKOP;
    output LOCK;


    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam PLLInst_0.CLKOK_BYPASS = "DISABLED" ;
    defparam PLLInst_0.CLKOS_BYPASS = "DISABLED" ;
    defparam PLLInst_0.CLKOP_BYPASS = "DISABLED" ;
    defparam PLLInst_0.PHASE_CNTL = "STATIC" ;
    defparam PLLInst_0.DUTY = 8 ;
    defparam PLLInst_0.PHASEADJ = "0.0" ;
    defparam PLLInst_0.CLKOK_DIV = 2 ;
    defparam PLLInst_0.CLKOP_DIV = 4 ;
    defparam PLLInst_0.CLKFB_DIV = 1 ;
    defparam PLLInst_0.CLKI_DIV = 1 ;
    // synopsys translate_on
    EPLLD PLLInst_0 (.CLKI(CLK), .CLKFB(CLKOP_t), .RST(RESET), .RSTK(scuba_vlo), 
        .DPAMODE(scuba_vlo), .DRPAI0(scuba_vlo), .DRPAI1(scuba_vlo), .DRPAI2(scuba_vlo), 
        .DRPAI3(scuba_vlo), .DFPAI0(scuba_vlo), .DFPAI1(scuba_vlo), .DFPAI2(scuba_vlo), 
        .DFPAI3(scuba_vlo), .CLKOP(CLKOP_t), .CLKOS(), .CLKOK(), .LOCK(LOCK), 
        .CLKINTFB())
             /* synthesis CLKOK_BYPASS="DISABLED" */
             /* synthesis CLKOS_BYPASS="DISABLED" */
             /* synthesis CLKOP_BYPASS="DISABLED" */
             /* synthesis PHASE_CNTL="STATIC" */
             /* synthesis DUTY="8" */
             /* synthesis PHASEADJ="0.0" */
             /* synthesis FREQUENCY_PIN_CLKOP="200.000000" */
             /* synthesis FREQUENCY_PIN_CLKI="200.000000" */
             /* synthesis FREQUENCY_PIN_CLKOK="50.000000" */
             /* synthesis CLKOK_DIV="2" */
             /* synthesis CLKOP_DIV="4" */
             /* synthesis CLKFB_DIV="1" */
             /* synthesis CLKI_DIV="1" */
             /* synthesis FIN="200.000000" */;

    assign CLKOP = CLKOP_t;


    // exemplar begin
    // exemplar attribute PLLInst_0 CLKOK_BYPASS DISABLED
    // exemplar attribute PLLInst_0 CLKOS_BYPASS DISABLED
    // exemplar attribute PLLInst_0 CLKOP_BYPASS DISABLED
    // exemplar attribute PLLInst_0 PHASE_CNTL STATIC
    // exemplar attribute PLLInst_0 DUTY 8
    // exemplar attribute PLLInst_0 PHASEADJ 0.0
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOP 200.000000
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKI 200.000000
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOK 50.000000
    // exemplar attribute PLLInst_0 CLKOK_DIV 2
    // exemplar attribute PLLInst_0 CLKOP_DIV 4
    // exemplar attribute PLLInst_0 CLKFB_DIV 1
    // exemplar attribute PLLInst_0 CLKI_DIV 1
    // exemplar attribute PLLInst_0 FIN 200.000000
    // exemplar end

endmodule
