/* Verilog netlist generated by SCUBA ispLever_v61_SP1_Build (17) */
/* Module Version: 3.4 */
/* C:\ispLEVER_6_1_ver37\ispfpga\bin\nt\scuba.exe -w -n pll_clk -lang verilog -synth synplify -arch mj5g00 -type pll -fin 200 -fclkop 200 -fclkop_tol 0.0 -delay_cntl STATIC -fdel 0 -fb_mode CLOCKTREE -noclkos -e  */
/* Wed Feb 14 10:36:31 2007 */


`timescale 1 ns / 1 ps
module clk_pll_xo (CLK, RESET, CLKOP, LOCK);
    input CLK;
    input RESET;
    output CLKOP;
    output LOCK;


    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam PLLCInst_0.DELAY_CNTL = "STATIC" ;
    defparam PLLCInst_0.FDEL = 0 ;
    defparam PLLCInst_0.DUTY = 4 ;
    defparam PLLCInst_0.PHASEADJ = 0 ;
    defparam PLLCInst_0.CLKOK_DIV = 2 ;
    defparam PLLCInst_0.CLKOP_DIV = 4 ;
    defparam PLLCInst_0.CLKFB_DIV = 1 ;
    defparam PLLCInst_0.CLKI_DIV = 1 ;
    // synopsys translate_on
    EHXPLLC PLLCInst_0 (.CLKI(CLK), .CLKFB(CLKOP_t), .RST(RESET), .DDAMODE(scuba_vlo), 
        .DDAIZR(scuba_vlo), .DDAILAG(scuba_vlo), .DDAIDEL0(scuba_vlo), .DDAIDEL1(scuba_vlo), 
        .DDAIDEL2(scuba_vlo), .CLKOP(CLKOP_t), .CLKOS(), .CLKOK(), .CLKINTFB(), 
        .LOCK(LOCK))
             /* synthesis DELAY_CNTL="STATIC" */
             /* synthesis FDEL="0" */
             /* synthesis DUTY="4" */
             /* synthesis PHASEADJ="0" */
             /* synthesis FREQUENCY_PIN_CLKOK="50.000000" */
             /* synthesis CLKOK_DIV="2" */
             /* synthesis FREQUENCY_PIN_CLKOS="200.000000" */
             /* synthesis FREQUENCY_PIN_CLKOP="200.000000" */
             /* synthesis FREQUENCY_PIN_CLKI="200.000000" */
             /* synthesis CLKOP_DIV="4" */
             /* synthesis CLKFB_DIV="1" */
             /* synthesis CLKI_DIV="1" */
             /* synthesis FIN="200.000000" */;

    assign CLKOP = CLKOP_t;


    // exemplar begin
    // exemplar attribute PLLCInst_0 DELAY_CNTL STATIC
    // exemplar attribute PLLCInst_0 FDEL 0
    // exemplar attribute PLLCInst_0 DUTY 4
    // exemplar attribute PLLCInst_0 PHASEADJ 0
    // exemplar attribute PLLCInst_0 FREQUENCY_PIN_CLKOK 50.000000
    // exemplar attribute PLLCInst_0 CLKOK_DIV 2
    // exemplar attribute PLLCInst_0 FREQUENCY_PIN_CLKOS 200.000000
    // exemplar attribute PLLCInst_0 FREQUENCY_PIN_CLKOP 200.000000
    // exemplar attribute PLLCInst_0 FREQUENCY_PIN_CLKI 200.000000
    // exemplar attribute PLLCInst_0 CLKOP_DIV 4
    // exemplar attribute PLLCInst_0 CLKFB_DIV 1
    // exemplar attribute PLLCInst_0 CLKI_DIV 1
    // exemplar attribute PLLCInst_0 FIN 200.000000
    // exemplar end

endmodule
