/* Verilog netlist generated by SCUBA ispLever_v61_SP1_Build (17) */
/* Module Version: 3.4 */
/* C:\ispLEVER_6_1_ver37\ispfpga\bin\nt\scuba.exe -w -n clk_pll -lang verilog -synth synplify -bus_exp 7 -bb -arch slayer -type pll -fin 200 -mfreq 200 -nfreq 100 -clkos_fdel 0 -fb 1 -use_rstn -clki_del 0 -clki_fdel 0 -clkfb_del 0 -clkfb_fdel 0 -reset_en -mtol 0.0 -ntol 0.0 -e  */
/* Thu Feb 15 16:25:27 2007 */


`timescale 1 ns / 1 ps
module clk_pll_sc (clk, resetn, clkop, clkos, lock)/* synthesis syn_noprune=1 */;// exemplar attribute clk_pll dont_touch true 
    input clk;
    input resetn;
    output clkop;
    output clkos;
    output lock;
    parameter SMI_OFFSET =  12'h410 ;

    wire clk_t;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam clk_pll_0_0.SMI_OFFSET = SMI_OFFSET ;
    // synopsys translate_off
    defparam clk_pll_0_0.GSR = "ENABLED" ;
    defparam clk_pll_0_0.CLKFB_FDEL = 0 ;
    defparam clk_pll_0_0.CLKI_FDEL = 0 ;
    defparam clk_pll_0_0.CLKOS_FDEL = 0 ;
    defparam clk_pll_0_0.CLKOS_VCODEL = 0 ;
    defparam clk_pll_0_0.PHASEADJ = 0 ;
    defparam clk_pll_0_0.CLKOS_MODE = "DIV" ;
    defparam clk_pll_0_0.CLKOP_MODE = "DIV" ;
    defparam clk_pll_0_0.CLKOS_DIV = 6 ;
    defparam clk_pll_0_0.CLKOP_DIV = 3 ;
    defparam clk_pll_0_0.CLKFB_DIV = 1 ;
    defparam clk_pll_0_0.CLKI_DIV = 1 ;
    // synopsys translate_on
    EHXPLLA clk_pll_0_0 (.SMIADDR9(scuba_vlo), .SMIADDR8(scuba_vlo), .SMIADDR7(scuba_vlo), 
        .SMIADDR6(scuba_vlo), .SMIADDR5(scuba_vlo), .SMIADDR4(scuba_vlo), 
        .SMIADDR3(scuba_vlo), .SMIADDR2(scuba_vlo), .SMIADDR1(scuba_vlo), 
        .SMIADDR0(scuba_vlo), .SMIRD(scuba_vlo), .SMIWR(scuba_vlo), .SMICLK(scuba_vlo), 
        .SMIWDATA(scuba_vlo), .SMIRSTN(scuba_vlo), .CLKI(clk_t), .CLKFB(clkop_t), 
        .RSTN(resetn), .CLKOP(clkop_t), .CLKOS(clkos_t), .LOCK(lock), .CLKINTFB(), 
        .SMIRDATA())
             /* synthesis ip_type="EHXPLLA" */
             /* synthesis FREQUENCY_PIN_CLKOS="100.000000" */
             /* synthesis FREQUENCY_PIN_CLKOP="200.000000" */
             /* synthesis FREQUENCY_PIN_CLKI="200.000000" */
             /* synthesis VCO_LOWERFREQ="DISABLED" */
             /* synthesis GMCFREQSEL="HIGH" */
             /* synthesis GSR="ENABLED" */
             /* synthesis SPREAD_DIV2="2" */
             /* synthesis SPREAD_DIV1="2" */
             /* synthesis SPREAD_DRIFT="1" */
             /* synthesis SPREAD="DISABLED" */
             /* synthesis CLKFB_FDEL="0" */
             /* synthesis CLKI_FDEL="0" */
             /* synthesis CLKFB_PDEL="DEL0" */
             /* synthesis CLKI_PDEL="DEL0" */
             /* synthesis LF_RESISTOR="0b111011" */
             /* synthesis LF_IX5UA="31" */
             /* synthesis CLKOS_FDEL="0" */
             /* synthesis CLKOS_VCODEL="0" */
             /* synthesis PHASEADJ="0" */
             /* synthesis CLKOS_MODE="DIV" */
             /* synthesis CLKOP_MODE="DIV" */
             /* synthesis CLKOS_DIV="6" */
             /* synthesis CLKOP_DIV="3" */
             /* synthesis CLKFB_DIV="1" */
             /* synthesis CLKI_DIV="1" */;

    assign clkos = clkos_t;
    assign clkop = clkop_t;
    assign clk_t = clk;


    // exemplar begin
    // exemplar attribute clk_pll_0_0 ip_type EHXPLLA
    // exemplar attribute clk_pll_0_0 FREQUENCY_PIN_CLKOS 100.000000
    // exemplar attribute clk_pll_0_0 FREQUENCY_PIN_CLKOP 200.000000
    // exemplar attribute clk_pll_0_0 FREQUENCY_PIN_CLKI 200.000000
    // exemplar attribute clk_pll_0_0 VCO_LOWERFREQ DISABLED
    // exemplar attribute clk_pll_0_0 GMCFREQSEL HIGH
    // exemplar attribute clk_pll_0_0 GSR ENABLED
    // exemplar attribute clk_pll_0_0 SPREAD_DIV2 2
    // exemplar attribute clk_pll_0_0 SPREAD_DIV1 2
    // exemplar attribute clk_pll_0_0 SPREAD_DRIFT 1
    // exemplar attribute clk_pll_0_0 SPREAD DISABLED
    // exemplar attribute clk_pll_0_0 CLKFB_FDEL 0
    // exemplar attribute clk_pll_0_0 CLKI_FDEL 0
    // exemplar attribute clk_pll_0_0 CLKFB_PDEL DEL0
    // exemplar attribute clk_pll_0_0 CLKI_PDEL DEL0
    // exemplar attribute clk_pll_0_0 LF_RESISTOR 0b111011
    // exemplar attribute clk_pll_0_0 LF_IX5UA 31
    // exemplar attribute clk_pll_0_0 CLKOS_FDEL 0
    // exemplar attribute clk_pll_0_0 CLKOS_VCODEL 0
    // exemplar attribute clk_pll_0_0 PHASEADJ 0
    // exemplar attribute clk_pll_0_0 CLKOS_MODE DIV
    // exemplar attribute clk_pll_0_0 CLKOP_MODE DIV
    // exemplar attribute clk_pll_0_0 CLKOS_DIV 6
    // exemplar attribute clk_pll_0_0 CLKOP_DIV 3
    // exemplar attribute clk_pll_0_0 CLKFB_DIV 1
    // exemplar attribute clk_pll_0_0 CLKI_DIV 1
    // exemplar end

endmodule
