/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Beta (70) */
/* Module Version: 1.0 */
/* Fri Feb 18 11:56:25 2011 */

/* parameterized module instance */
counter_EFB __ (.tc_clki( ), .tc_rstn( ), .tc_int( ), .tc_oc( ));
