/* Verilog netlist generated by SCUBA Diamond_1.3_Production (92) */
/* Module Version: 3.5 */
/* C:/lscc/1.3_20110802-1_3p.92/diamond/1.3/ispfpga/bin/nt/scuba -w -bus_exp 7 -bb -arch xo2c00 -type sspram -num_rows 16 -data_width 12 -memformat bin -n pmi_distributed_spramXbnonen12416 -pmi -lang verilog  */
/* Fri Oct 14 15:11:30 2011 */


`timescale 1 ns / 1 ps
module pmi_distributed_spramXbnonen12416 (Address, Data, Clock, WE, 
    ClockEn, Reset, Q);
    input wire [3:0] Address;
    input wire [11:0] Data;
    input wire Clock;
    input wire WE;
    input wire ClockEn;
    input wire Reset;
    output wire [11:0] Q;

    wire scuba_vlo;
    wire scuba_vhi;
    wire dec0_wre3;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    defparam LUT4_0.initval =  16'h8000 ;
    ROM16X1A LUT4_0 (.AD3(WE), .AD2(ClockEn), .AD1(scuba_vhi), .AD0(scuba_vhi), 
        .DO0(dec0_wre3));

    defparam mem_0_0.initval = "0x0000000000000000" ;
    SPR16X4C mem_0_0 (.DI0(Data[8]), .DI1(Data[9]), .DI2(Data[10]), .DI3(Data[11]), 
        .CK(Clock), .WRE(dec0_wre3), .AD0(Address[0]), .AD1(Address[1]), 
        .AD2(Address[2]), .AD3(Address[3]), .DO0(Q[8]), .DO1(Q[9]), .DO2(Q[10]), 
        .DO3(Q[11]))
             /* synthesis MEM_INIT_FILE="(0-15)(0-3)" */
             /* synthesis MEM_LPC_FILE="pmi_distributed_spramXbnonen12416__PMI__16__12__12B" */
             /* synthesis COMP="mem_0_0" */;

    defparam mem_0_1.initval = "0x0000000000000000" ;
    SPR16X4C mem_0_1 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), .DI3(Data[7]), 
        .CK(Clock), .WRE(dec0_wre3), .AD0(Address[0]), .AD1(Address[1]), 
        .AD2(Address[2]), .AD3(Address[3]), .DO0(Q[4]), .DO1(Q[5]), .DO2(Q[6]), 
        .DO3(Q[7]))
             /* synthesis MEM_INIT_FILE="(0-15)(4-7)" */
             /* synthesis MEM_LPC_FILE="pmi_distributed_spramXbnonen12416__PMI__16__12__12B" */
             /* synthesis COMP="mem_0_1" */;

    defparam mem_0_2.initval = "0x0000000000000000" ;
    SPR16X4C mem_0_2 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), .DI3(Data[3]), 
        .CK(Clock), .WRE(dec0_wre3), .AD0(Address[0]), .AD1(Address[1]), 
        .AD2(Address[2]), .AD3(Address[3]), .DO0(Q[0]), .DO1(Q[1]), .DO2(Q[2]), 
        .DO3(Q[3]))
             /* synthesis MEM_INIT_FILE="(0-15)(8-11)" */
             /* synthesis MEM_LPC_FILE="pmi_distributed_spramXbnonen12416__PMI__16__12__12B" */
             /* synthesis COMP="mem_0_2" */;



    // exemplar begin
    // exemplar attribute mem_0_0 MEM_INIT_FILE (0-15)(0-3)
    // exemplar attribute mem_0_0 MEM_LPC_FILE pmi_distributed_spramXbnonen12416__PMI__16__12__12B
    // exemplar attribute mem_0_0 COMP mem_0_0
    // exemplar attribute mem_0_1 MEM_INIT_FILE (0-15)(4-7)
    // exemplar attribute mem_0_1 MEM_LPC_FILE pmi_distributed_spramXbnonen12416__PMI__16__12__12B
    // exemplar attribute mem_0_1 COMP mem_0_1
    // exemplar attribute mem_0_2 MEM_INIT_FILE (0-15)(8-11)
    // exemplar attribute mem_0_2 MEM_LPC_FILE pmi_distributed_spramXbnonen12416__PMI__16__12__12B
    // exemplar attribute mem_0_2 COMP mem_0_2
    // exemplar end

endmodule
