/* Verilog module instantiation template generated by SCUBA ispLever_v8.1_ALPHA_Build (578) */
/* Module Version: 3.1 */
/* Fri Apr 09 16:13:44 2010 */

/* parameterized module instance */
add8 __ (.DataA( ), .DataB( ), .Result( ));
