@TM:1255366228
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF257 :"":0:0:0:-1|Gated clock conversion enabled 
@N: MF276 :"":0:0:0:-1|Gated clock conversion enabled, but no gated clocks found in design 
@N: MF333 :"":0:0:0:-1|Generated clock conversion enabled, but no generated clocks found in design 
@N: MT206 :"":0:0:0:-1|Autoconstrain Mode is ON
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@N:  :"C:\Documents and Settings\bcaslis\My Documents\balidesigns\mixedcounter\source\typecount8.vhd":8:7:8:12|M
@N: CD630 :"C:\Documents and Settings\bcaslis\My Documents\balidesigns\mixedcounter\source\typecount8.vhd":8:7:8:12|M
@A:  :"C:\Documents and Settings\bcaslis\My Documents\balidesigns\mixedcounter\source\typecount8.vhd":22:4:22:5|M
@N:  :"c:\documents and settings\bcaslis\my documents\balidesigns\mixedcounter\source\typecount8.vhd":22:4:22:5|M
@N: CD720 :"C:\ispTOOLS7_2\synpbase\lib\vhd\std.vhd":123:18:123:21|M
