// =============================================================================
//                           COPYRIGHT NOTICE
// Copyright 2011 (c) Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// This confidential and proprietary software may be used only as authorised by
// a licensing agreement from Lattice Semiconductor Corporation.
// The entire notice above must be reproduced on all authorized copies and
// copies may only be made to the extent permitted by a licensing agreement from
// Lattice Semiconductor Corporation.
//
// Lattice Semiconductor Corporation       TEL  : 1-800-Lattice (USA and Canada)
// 5555 NE Moore Court                            503-268-8001 (other locations)
// Hillsboro, OR 97124                     web  : http://www.latticesemi.com/
// U.S.A                                   email: techsupport@latticesemi.com
// =============================================================================
//                         FILE DETAILS         
// Project               : Platform Manager 2
// File                  : ASCVM_RAM_EBR.v
// Title                 : Usage defined macros for Analog Sense and Control Virtual Machine
// Dependencies          : Supports ASCVM.v & ASCVM_DATAPATH.v.
//                       : 
// Description           : EBR for ASDVM RDAT and WDAT frame storages.
// =============================================================================
//                        REVISION HISTORY
// Version               : 0.1
// Changes Made          : Initial Release
// Author(s)             : Dan Sides
// Mod. Date             : Feb 2012
// =============================================================================

/* Verilog netlist generated by SCUBA Diamond_1.3_Beta (270) */
/* Module Version: 7.1 */
/* C:\lscc\diamond\1.3\ispfpga\bin\nt\scuba.exe -w -lang verilog -synth synplify -bus_exp 7 -bb -arch xo2c00 -type bram -wp 10 -rp 1000 -addr_width 3 -data_width 16 -num_rows 5 -cascade 11 -mem_init0 -writemode NORMAL -e  */
/* Wed Aug 24 13:12:54 2011 */


`timescale 1 ns / 1 ps
module ASCVM_RAM_EBR (Clock, ClockEn, Reset, WE, Address, Data, Q);
    input wire Clock;
    input wire ClockEn;
    input wire Reset;
    input wire WE;
    input wire [2:0] Address;
    input wire [15:0] Data;
    output wire [15:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam ASCVM_RAM_EBR_0_0_0_0.INIT_DATA = "STATIC" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_1F = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_1E = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_1D = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_1C = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_1B = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_1A = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_19 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_18 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_17 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_16 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_15 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_14 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_13 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_12 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_11 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_10 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_0F = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_0E = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_0D = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_0C = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_0B = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_0A = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_09 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_08 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_07 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_06 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_05 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_04 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_03 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_02 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_01 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.INITVAL_00 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.CSDECODE_B = "0b000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.CSDECODE_A = "0b000" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.WRITEMODE_B = "NORMAL" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.WRITEMODE_A = "NORMAL" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.GSR = "ENABLED" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.RESETMODE = "ASYNC" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.REGMODE_B = "NOREG" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.REGMODE_A = "NOREG" ;
    defparam ASCVM_RAM_EBR_0_0_0_0.DATA_WIDTH_B = 9 ;
    defparam ASCVM_RAM_EBR_0_0_0_0.DATA_WIDTH_A = 9 ;
    DP8KC ASCVM_RAM_EBR_0_0_0_0 (.DIA8(Data[8]), .DIA7(Data[7]), .DIA6(Data[6]), 
        .DIA5(Data[5]), .DIA4(Data[4]), .DIA3(Data[3]), .DIA2(Data[2]), 
        .DIA1(Data[1]), .DIA0(Data[0]), .ADA12(scuba_vlo), .ADA11(scuba_vlo), 
        .ADA10(scuba_vlo), .ADA9(scuba_vlo), .ADA8(scuba_vlo), .ADA7(scuba_vlo), 
        .ADA6(scuba_vlo), .ADA5(Address[2]), .ADA4(Address[1]), .ADA3(Address[0]), 
        .ADA2(scuba_vlo), .ADA1(scuba_vlo), .ADA0(scuba_vhi), .CEA(ClockEn), 
        .OCEA(ClockEn), .CLKA(Clock), .WEA(WE), .CSA2(scuba_vlo), .CSA1(scuba_vlo), 
        .CSA0(scuba_vlo), .RSTA(Reset), .DIB8(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB6(Data[15]), .DIB5(Data[14]), .DIB4(Data[13]), .DIB3(Data[12]), 
        .DIB2(Data[11]), .DIB1(Data[10]), .DIB0(Data[9]), .ADB12(scuba_vhi), 
        .ADB11(scuba_vlo), .ADB10(scuba_vlo), .ADB9(scuba_vlo), .ADB8(scuba_vlo), 
        .ADB7(scuba_vlo), .ADB6(scuba_vlo), .ADB5(Address[2]), .ADB4(Address[1]), 
        .ADB3(Address[0]), .ADB2(scuba_vlo), .ADB1(scuba_vlo), .ADB0(scuba_vhi), 
        .CEB(ClockEn), .OCEB(ClockEn), .CLKB(Clock), .WEB(WE), .CSB2(scuba_vlo), 
        .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), .DOA8(Q[8]), .DOA7(Q[7]), 
        .DOA6(Q[6]), .DOA5(Q[5]), .DOA4(Q[4]), .DOA3(Q[3]), .DOA2(Q[2]), 
        .DOA1(Q[1]), .DOA0(Q[0]), .DOB8(), .DOB7(), .DOB6(Q[15]), .DOB5(Q[14]), 
        .DOB4(Q[13]), .DOB3(Q[12]), .DOB2(Q[11]), .DOB1(Q[10]), .DOB0(Q[9]))
             /* synthesis MEM_LPC_FILE="ASCVM_RAM_EBR.lpc" */
             /* synthesis MEM_INIT_FILE="INIT_ALL_0s" */;



    // exemplar begin
    // exemplar attribute ASCVM_RAM_EBR_0_0_0_0 MEM_LPC_FILE ASCVM_RAM_EBR.lpc
    // exemplar attribute ASCVM_RAM_EBR_0_0_0_0 MEM_INIT_FILE INIT_ALL_0s
    // exemplar end

endmodule
