-- NOTE: Do not edit this file.
-- Auto generated by All Verilog Functional Simulation Models
--
vlib work
vlog decoder_1553.v 
vlog encoder_1553.v 

vlog clk_pll_all.v  
-- for ecp2, ecp2m, xp2, ec, ecp, xp

vlog top.v
vlog enc_dec_tb.v

-- vsim enc_dec_tb -L xp_vlg
-- vsim enc_dec_tb -L ec_vlg
-- vsim enc_dec_tb -L ecp_vlg

-- vsim enc_dec_tb -L xp2_vlg
-- vsim enc_dec_tb -L ecp2m_vlg
vsim enc_dec_tb -L ecp2_vlg

do wave_enc_dec.do enc_dec_tb
-- End
