/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Beta (70) */
/* Module Version: 3.5 */
/* Thu Feb 17 15:45:04 2011 */

/* parameterized module instance */
RAM_single_port __ (.Address( ), .Data( ), .Clock( ), .WE( ), 
    .ClockEn( ), .Q( ));
